name: actions-ui
on:
  push:
    branches:
      - main
jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
        project-template: ['empty', 'antdv', 'element', 'quasar', 'vuetify']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm add -g zova-cli
      - run: zova :create:project ${{ matrix.project-template }}-${{ matrix.node-version }} --template=${{ matrix.project-template }}
      - name: pnpm install
        run: pnpm install --force --no-frozen-lockfile
        working-directory: ${{ matrix.project-template }}-${{ matrix.node-version }}
      - name: suite
        run: zova :create:suite test-demo --description --author
        working-directory: ${{ matrix.project-template }}-${{ matrix.node-version }}
      - name: module
        run: zova :create:module test-demo --template=basic --suite=test-demo --description --author --cicd
        working-directory: ${{ matrix.project-template }}-${{ matrix.node-version }}
      - name: pnpm install --force
        run: pnpm install --force --no-frozen-lockfile
        working-directory: ${{ matrix.project-template }}-${{ matrix.node-version }}
      - name: page
        run: zova :create:page first --module=test-demo
        working-directory: ${{ matrix.project-template }}-${{ matrix.node-version }}
      - name: component
        run: zova :create:component child --module=test-demo
        working-directory: ${{ matrix.project-template }}-${{ matrix.node-version }}
      - name: npm run build
        run: npm run build
        working-directory: ${{ matrix.project-template }}-${{ matrix.node-version }}
